/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "opamp-java"

dependencyResolutionManagement {
  repositories {
    mavenCentral()
    mavenLocal()
  }
}

pluginManagement {
  plugins {
    id("com.google.protobuf") version "0.8.19"
    id("nebula.release") version "16.0.0"
  }
}

include(":proto")
